

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigInteger;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
/**
 *
 * @author agupt263
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Socket s=null;
    
    String id=null;
    String pass=null;
    profileobject profile=null;
    
    Dashboard(Socket s,ObjectOutputStream out,ObjectInputStream in, String id, String pass) {
        initComponents();
        saveb.setVisible(false);
        passcodel.setVisible(false);
        passcodell.setVisible(false);
        cancelb.setVisible(false);
        this.s=s;
        this.id=id;
        this.pass=pass;
        this.out=out;
        this.in=in;
        load();
        loadvalues();
    }

    private Dashboard() {
        initComponents();
        saveb.setVisible(false);
        passcodel.setVisible(false);
        passcodell.setVisible(false);
    }
    
    private void loadvalues() {
        
        Image timage = profile.getimage().getImage();
        Image ntimage = timage.getScaledInstance(photo.getWidth(), photo.getHeight(), java.awt.Image.SCALE_SMOOTH);
        photo.removeAll();
        photo.setIcon(new ImageIcon(ntimage));
        
        
        namel.setText(profile.getusername());
        if (profile.getdesignation()==2)
        {
            designationl.setText("Admin");
        }
        else
        {
            designationl.setText("Developer");
        }
        numberl.setText(""+profile.getphonenuber());
        emaill.setText(profile.getemail());
        label1.setText(""+profile.getuserid());
    }
    ObjectOutputStream out = null;
    ObjectInputStream in=null;
    private void load()
    {
        try 
        {
            out.writeObject("load");
            out.flush();
            out.reset();
            
            profile=(profileobject) in.readObject();
            orignalcopy=profile;
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void editmodeoff()
    {
        editpicbool=false;
        namel.setEditable(false);
        numberl.setEditable(false);
        emaill.setEditable(false);
        cancelb.setVisible(false);
        saveb.setVisible(false);
        passcodell.setVisible(false);
        passcodel.setVisible(false);
    }
    profileobject orignalcopy=null;
    private void editmodeon()
    {
        
        editpicbool=true;
        namel.setEditable(true);
        numberl.setEditable(true);
        emaill.setEditable(true);
        
        cancelb.setVisible(true);
        saveb.setVisible(true);
        passcodell.setVisible(true);
        passcodel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutb = new javax.swing.JButton();
        editprofileb = new javax.swing.JButton();
        designationl1 = new javax.swing.JLabel();
        designationl2 = new javax.swing.JLabel();
        designationl3 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        designationl = new javax.swing.JTextField();
        namel = new javax.swing.JTextField();
        numberl = new javax.swing.JTextField();
        emaill = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        saveb = new javax.swing.JButton();
        passcodell = new javax.swing.JLabel();
        passcodel = new javax.swing.JTextField();
        cancelb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        logoutb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutb.setText("Logout");
        logoutb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbMouseClicked(evt);
            }
        });

        editprofileb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editprofileb.setText("Edit Profile");
        editprofileb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editprofileb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editprofilebMouseClicked(evt);
            }
        });

        designationl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designationl1.setText("Designation:");
        designationl1.setToolTipText("Name");

        designationl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designationl2.setText("Mobile Number:");
        designationl2.setToolTipText("Name");

        designationl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        designationl3.setText("Email ID:");
        designationl3.setToolTipText("Name");

        photo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });

        designationl.setEditable(false);

        namel.setEditable(false);
        namel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namelActionPerformed(evt);
            }
        });

        numberl.setEditable(false);

        emaill.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User ID: ");

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        saveb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveb.setText("Save ");
        saveb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebMouseClicked(evt);
            }
        });

        passcodell.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passcodell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passcodell.setText("Passcode:");
        passcodell.setToolTipText("Name");

        passcodel.setOpaque(false);

        cancelb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelb.setText("Cancel");
        cancelb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("User Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveb)
                                .addGap(18, 18, 18)
                                .addComponent(cancelb))
                            .addComponent(designationl3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passcodell, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editprofileb)
                                    .addGap(18, 18, 18)
                                    .addComponent(logoutb))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(designationl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(designationl2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(namel)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(designationl)
                                        .addComponent(numberl, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(emaill, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passcodel, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutb)
                            .addComponent(editprofileb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(namel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(photo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(designationl, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(designationl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(designationl2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(numberl))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emaill, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationl3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passcodel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passcodell, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveb)
                    .addComponent(cancelb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namelActionPerformed

    private void editprofilebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editprofilebMouseClicked
        editmodeon();
    }//GEN-LAST:event_editprofilebMouseClicked
    
    private boolean editpicbool=false;
    private void photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoMouseClicked
        if (editpicbool)
        {
            JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
            j.addChoosableFileFilter(new FileNameExtensionFilter("*.Images","jpeg", "jpg","gif","png"));
            j.setAcceptAllFileFilterUsed(false);
            int result = j.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = j.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                File pathToFile = new File(path);
                ImageIcon candidateimage = new ImageIcon(pathToFile.getAbsolutePath());
                profile.setimage(candidateimage);
                
                Image timage = candidateimage.getImage();
                Image ntimage = timage.getScaledInstance(photo.getWidth(), photo.getHeight(), java.awt.Image.SCALE_SMOOTH);
                photo.setIcon(new ImageIcon(ntimage));
            }
            
        }
    }//GEN-LAST:event_photoMouseClicked

        
    
    
    private void saveupdateprofile()
    {
        profile.setemail(emaill.getText());
        profile.setphonenumber(new BigInteger(numberl.getText()));
        profile.setusername(namel.getText());
    }
    
    public boolean emailformatcheck( String email )  
    {
        try {
                out.writeObject("emailcheck");
                out.flush();
                out.reset();
                
                out.writeObject(email);
                out.flush();
                out.reset();
                
                Boolean ret=in.readBoolean();
                //System.out.println("EMAIL HAI:"+ret);
                return ret;
            
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    public  boolean phonenumvercheck(String s) 
    { 
        try {
                out.writeObject("phonenumbercheck");
                out.flush();
                out.reset();
                
                out.writeObject(s);
                out.flush();
                out.reset();
                
                Boolean ret=in.readBoolean();
                //System.out.println("PHONE HAI:"+ret);
                return ret;
            
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    } 
    private boolean OTPconfirme()
    {
        boolean ret=false;
        try 
        {
            out.writeObject("EditConfirmOTP"); 
            out.flush();
            out.reset();
            
            out.writeObject(numberl.getText()); 
            out.flush();
            out.reset();
            out.writeObject(emaill.getText()); 
            out.flush();
            out.reset();
            String t=JOptionPane.showInputDialog(rootPane, "Enter Your OTP");
            if (t!=null)
            {
                if (!t.isEmpty() && t!=(""+JOptionPane.CANCEL_OPTION))
                {
                    out.writeObject(t);
                    out.flush();
                    out.reset();
                    
                    ret=in.readBoolean();
                }
                else if (t.isEmpty() && t!=(""+JOptionPane.CANCEL_OPTION))
                {
                    JOptionPane.showMessageDialog(this, "Enter OTP", "No OTP Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                out.writeObject("cancelEditConfirmOTP");
                out.flush();
                out.reset();
            }

        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ret;
    }
    
    private void savebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebMouseClicked
        if (emailformatcheck(emaill.getText()) && phonenumvercheck(numberl.getText()))
        {
            int a=JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Save The Changes ?");
            if (a==JOptionPane.YES_OPTION)
            {
                if(OTPconfirme())
                {
                    try 
                    {
                        saveupdateprofile();
                        out.writeObject("saveeditprofile");
                        out.flush();
                        out.reset();
                        orignalcopy=profile;
                        if (passcodel.getText().isEmpty())
                        {
                            out.writeObject("savewithoutpasscode");
                            out.flush();
                            out.reset();

                            out.writeObject(profile);
                            out.flush();
                            out.reset();
                        }
                        else
                        {
                            out.writeObject("savewithpasscode");
                            out.flush();
                            out.reset();

                            out.writeObject(profile);
                            out.flush();
                            out.reset();

                            out.writeObject(passcodel.getText());
                            out.flush();
                            out.reset();
                        }

                        editmodeoff();

                    } catch (IOException ex) {
                        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Entered wrong OTP or canceled operation or OTP Time Expired!","OTP Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Email or Phone number Format is invalid !","Contact info Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_savebMouseClicked

    private void cancelbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbMouseClicked
        profile=orignalcopy;
        profile.setimage(orignalcopy.getimage());
        loadvalues();
        editmodeoff();
    }//GEN-LAST:event_cancelbMouseClicked

    private void close_connection()
    {
        try 
        {
            out.writeObject("fin_connection");
            out.flush();
            out.reset();
            
            out.close();
            in.close();
            s.close();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void logoutbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbMouseClicked
       close_connection();
       Login ob=new Login();
       ob.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutbMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close_connection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelb;
    private javax.swing.JTextField designationl;
    private javax.swing.JLabel designationl1;
    private javax.swing.JLabel designationl2;
    private javax.swing.JLabel designationl3;
    private javax.swing.JButton editprofileb;
    private javax.swing.JTextField emaill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private javax.swing.JButton logoutb;
    private javax.swing.JTextField namel;
    private javax.swing.JTextField numberl;
    private javax.swing.JTextField passcodel;
    private javax.swing.JLabel passcodell;
    private javax.swing.JLabel photo;
    private javax.swing.JButton saveb;
    // End of variables declaration//GEN-END:variables

    
}
